"""Change transaction_reference to composite unique constraint with investigation_id

Revision ID: 9c6c396abe3e
Revises: bc82f014740b
Create Date: 2026-09-05 14:52:16.002383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c6c396abe3e'
down_revision: Union[str, None] = 'bc82f014740b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_transaction_reference', table_name='transactions')
    op.create_index(op.f('ix_transactions_transaction_reference'), 'transactions', ['transaction_reference'], unique=False)
    op.create_unique_constraint('uq_investigation_transaction_reference', 'transactions', ['investigation_id', 'transaction_reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_investigation_transaction_reference', 'transactions', type_='unique')
    op.drop_index(op.f('ix_transactions_transaction_reference'), table_name='transactions')
    op.create_index('ix_transactions_transaction_reference', 'transactions', ['transaction_reference'], unique=True)
    # ### end Alembic commands ###
